# HW4 
    통계학과 20학번 김상현 (22010687)

In [5]:
import numpy as np
import colorama

def print_colored_matrix(M):
    stringM = ""
    num_rows, num_cols = M.shape
    
    for n in range(num_cols):
        for m in range(num_rows):
            str_member = f'{colorama.Fore.BLACK}{str(M[m,n])}'
            if M[m,n] <= -10: 
                sep = " "
                str_member = f'{colorama.Fore.RED}{str(M[m,n])}'
            elif M[m,n] < 0:
                sep = "  "
                str_member = f'{colorama.Fore.RED}{str(M[m,n])}'
            elif M[m,n] < 10: sep = "   "
            else: sep = "  "
            stringM = stringM + sep + str_member 
        if n < num_cols - 1: stringM = stringM + "\n"
    print(stringM)
    print('\033[0m')

# 1.

아래 numpy array ```A```를 ```print_colored_matrix``` 함수를 이용하여 출력해 보라.

In [28]:
A = np.array([[-1, -2, -3, -4, -5],
              [-6, -7, 8, -9, 10],
              [-11, -12, -13, -14, 15],
              [-16, -17, -18, -19, 20],
              [-21, 22, 23, -24, -25]])
print(A)
print_colored_matrix(A)

[[ -1  -2  -3  -4  -5]
 [ -6  -7   8  -9  10]
 [-11 -12 -13 -14  15]
 [-16 -17 -18 -19  20]
 [-21  22  23 -24 -25]]
  -1  -6 -11 -16 -21
  -2  -7 -12 -17  22
  -3   8 -13 -18  23
  -4  -9 -14 -19 -24
  -5  10  15  20 -25



# 2.
```A```의 왼쪽 위에서 오른쪽 아래로 내려가는 대각선의 값들이 모두 음수인지 체크하는 코드를 작성하라. 모두 음수이면 ```True```로 체크한다. 마찬가지로 ```A```의 왼쪽 아래에서 오른쪽 위로 올라가는 대각선의 값들이 모두 음수인지 체크하는 코드를 작성하라.

###### (1) 왼쪽 위에서 오른쪽 아래로 내려가는 대각선 값 음수 체크

In [29]:
#sol(1)
a=np.diag(A)  
ans1 = 0

for i in range(len(a)):
    if a[i]<0:
        ans1 = ans1 + 1
    if ans1 == len(a):
        print("True")

True


In [30]:
#sol(2)

np.all(np.diag(A) < 0)


True

###### (2) 왼쪽 아래에서 오른쪽 위로 올라가는 대각선 값 음수 체크

In [31]:
#sol(1) 
a=np.diag(A[::-1])
ans1 = 0

for i in range(len(a)):
    if a[i]<0:
        ans1 = ans1 + 1
    if ans1 == len(a):
        print("True")

True


In [32]:
#sol(2)

np.all(np.diag(A[::-1] < 0))

True

# 3.
모두 음수로 이루어진 행이나 열이 총 몇 개인지 세는 코드를 작성하라.

In [33]:
def count(matrix):
    columns=0
    rows=0
    lenrow = matrix.shape[0] # 행의 크기
    lencolumns = matrix.shape[1] # 열의 크기  
    
    for t in range(lenrow):   
        ans = 0
        for i in range(lencolumns): 
            if matrix[t,i] < 0: 
                ans = ans + 1
            if ans == lencolumns:
                rows = rows + 1 
                
    for i in range(lencolumns):
        ans = 0
        for t in range(lenrow):
            if matrix[t,i] < 0:
                ans = ans + 1
            if ans == lenrow:
                columns = columns + 1
   
    print("모두 음수로 이루어진 열의 갯수는" ,columns,"개 입니다") 
    print("모두 음수로 이루어진 행의 갯수는",rows,"개 입니다")


In [34]:
count(A)

모두 음수로 이루어진 열의 갯수는 2 개 입니다
모두 음수로 이루어진 행의 갯수는 1 개 입니다


# 4.
```np.random.choice```를 이용하여, 1이상 25이하 정수가 랜덤으로 구성된 5 by 5 행렬을 만드는 코드를 작성하라. 이렇게 만든 행렬을 ```B```라고 하자.

In [6]:
B = np.random.choice(range(1,26),(5,5))
B


array([[ 1,  9,  9, 19,  6],
       [23,  3, 18, 16, 14],
       [11, 12, 12, 11, 21],
       [ 2, 22, 16, 25,  8],
       [21, 17, 10,  5,  2]])

# 5.
1부터 25까지 정수로 이루어진 리스트, ```remains```를 만들라. ```remains```에서 숫자 하나를 랜덤으로 선택하여 ```selected```라고 하자. 이 숫자를 ```remains```에서 삭제하는 코드를 작성하라.

In [7]:
import random
remains = list(range(1,26))
print(remains)
selected=random.choice(remains)
print(selected)
remains.remove(selected)
print(remains)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
11
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]


# 7.
위 과정을 20번 반복하는 코드를 작성하라. 즉, 다음의 과정을 20번 반복하도록 하라.
* 위에서 선택된 숫자 ```selected```를 ```B```에서 음수로 만드는 코드를 작성하라. 다음 코드를 참고하라.

* ```B[B == selected] = -selected```

* ```print_colored_matrix```로 ```B```를 출력하라.

In [17]:
ans=[]
remains = list(range(1,26))
for _ in range(20):
    selected=random.choice(remains)
    remains.remove(selected)
    B[B == selected] = -selected
    ans.append(selected)

print("선택 받지 못한 숫자들:")
print(remains)
print("음수로 변환할 숫자들:")
print(ans)
print("colored_matrix 적용한 B:")
print_colored_matrix(B)

선택 받지 못한 숫자들:
[3, 4, 13, 19, 23]
음수로 변환할 숫자들:
[18, 7, 8, 22, 20, 24, 11, 2, 6, 14, 5, 9, 15, 25, 1, 12, 17, 10, 16, 21]
colored_matrix 적용한 B:
  -1 -23 -11  -2 -21
  -9  -3 -12 -22 -17
  -9 -18 -12 -16 -10
 -19 -16 -11 -25  -5
  -6 -14 -21  -8  -2



# 8.
```B```에서 모두 음수로 이루어진 행이나 열, 대각선이 총 몇 개인지 세는 코드를 작성하라.

In [38]:
def count_1(matrix):
    columns=0
    rows=0
    diagonal_1 = 0
    diagonal_2 = 0
    lenrow = matrix.shape[0] # 행의 크기
    lencolumns = matrix.shape[1] # 열의 크기     


    for t in range(lenrow):   
        ans = 0
        for i in range(lencolumns): 
            if matrix[t,i] < 0: 
                ans = ans + 1
            if ans == lencolumns:
                rows = rows + 1 
                
    for i in range(lencolumns):
        ans = 0
        for t in range(lenrow):
            if matrix[t,i] < 0:
                ans = ans + 1
            if ans == lenrow:
                columns = columns + 1         

    x = np.diag(matrix)
    ans = 0
    for i in range(len(x)):
        if x[i] < 0:
            ans = ans + 1
        if ans == len(x):
            diagonal_1 = diagonal_1 + 1
        
    y = np.diag(matrix[::-1])
    ans = 0
    for i in range(len(y)):
        if y[i] < 0:
            ans = ans + 1
        if ans == len(y):
            diagonal_2 = diagonal_2 + 1
            
    diagonal = diagonal_1 + diagonal_2
    
    print(matrix)
    print("모두 음수로 이루어진 열의 갯수는" ,columns,"개 입니다") 
    print("모두 음수로 이루어진 행의 갯수는",rows,"개 입니다")
    print("모두 음수로 이루어진 대각선의 갯수는",diagonal,"개 입니다")


count_1(B)

[[-17 -10  16  -3 -11]
 [ -8 -15 -12  13 -20]
 [ -4  13  16  16  -9]
 [ -4  24 -22  -7 -17]
 [-14  -6 -20 -15 -22]]
모두 음수로 이루어진 열의 갯수는 2 개 입니다
모두 음수로 이루어진 행의 갯수는 1 개 입니다
모두 음수로 이루어진 대각선의 갯수는 0 개 입니다


# 9.
4번부터 8번까지의 내용을 하나의 셀에 작성하여 몇 번 돌려보면서, 코드에 잘못된 점이 없는지 체크해 보라.

In [39]:
import random
import numpy as np

B = np.random.choice(range(1,26),(5,5))
print("생성된 행렬 B:")
print(B)
remains = list(range(1,26))
ans=[]
for _ in range(20):
    selected=random.choice(remains)
    remains.remove(selected)
    B[B == selected] = -selected
    ans.append(selected)

print("선택 받지 못한 숫자들:")
print(remains)
print("음수로 변환할 숫자들:")
print(ans)
print("음수로 변환된 행렬 B:")
print(B)
print("colored_matrix 적용한 B:")
print_colored_matrix(B)

def count_1(matrix):
    columns=0
    rows=0
    diagonal_1 = 0
    diagonal_2 = 0
    lenrow = matrix.shape[0] # 행의 크기
    lencolumns = matrix.shape[1] # 열의 크기     


    for t in range(lenrow):   
        ans = 0
        for i in range(lencolumns): 
            if matrix[t,i] < 0: 
                ans = ans + 1
            if ans == lencolumns:
                rows = rows + 1 
                
    for i in range(lencolumns):
        ans = 0
        for t in range(lenrow):
            if matrix[t,i] < 0:
                ans = ans + 1
            if ans == lenrow:
                columns = columns + 1         

    x = np.diag(matrix)
    ans = 0
    for i in range(len(x)):
        if x[i] < 0:
            ans = ans + 1
        if ans == len(x):
            diagonal_1 = diagonal_1 + 1
        
    y = np.diag(matrix[::-1])
    ans = 0
    for i in range(len(y)):
        if y[i] < 0:
            ans = ans + 1
        if ans == len(y):
            diagonal_2 = diagonal_2 + 1
            
    diagonal = diagonal_1 + diagonal_2

    print("모두 음수로 이루어진 열의 갯수는" ,columns,"개 입니다") 
    print("모두 음수로 이루어진 행의 갯수는",rows,"개 입니다")
    print("모두 음수로 이루어진 대각선의 갯수는",diagonal,"개 입니다")

    
count_1(B)

생성된 행렬 B:
[[15  7  9  1 12]
 [10  7  8 24  5]
 [ 8 23 20  4  8]
 [ 4 25 22 21 19]
 [21 13 14  7  6]]
선택 받지 못한 숫자들:
[3, 9, 10, 16, 18]
음수로 변환할 숫자들:
[19, 7, 14, 24, 22, 15, 20, 12, 4, 1, 25, 11, 13, 8, 6, 17, 23, 5, 21, 2]
음수로 변환된 행렬 B:
[[-15  -7   9  -1 -12]
 [ 10  -7  -8 -24  -5]
 [ -8 -23 -20  -4  -8]
 [ -4 -25 -22 -21 -19]
 [-21 -13 -14  -7  -6]]
colored_matrix 적용한 B:
 -15  10  -8  -4 -21
  -7  -7 -23 -25 -13
   9  -8 -20 -22 -14
  -1 -24  -4 -21  -7
 -12  -5  -8 -19  -6

모두 음수로 이루어진 열의 갯수는 3 개 입니다
모두 음수로 이루어진 행의 갯수는 3 개 입니다
모두 음수로 이루어진 대각선의 갯수는 2 개 입니다
